names: 
  - xeus-cling
  - java_env
  - beakerx
channels:
  - conda-forge
  - defaults
dependencies:
  - xeus-cling=0.13.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - notebook
  - matplotlib
  - numpy
  - vpython
  - pandas
  - metakernel
  - scijava-jupyter-kernel
  - ipywidgets
  - beakerx
  - pip:
    - calysto_scheme
    - metakernel
    - numpy
    - calysto
    - yasi
    - mlxtend
    - vpython
    - jupyterlab-vpython
